services:
    redis-stack:
        image: redis/redis-stack:latest
        restart: always
        volumes:
          - ./redis/:/data

    dashboard:
        build: ./dashboard
        depends_on:
          - redis-stack
        env_file: ./dashboard/.env.local
        restart: always

    discord-bot:
        build: ./discord-bot
        depends_on:
          - redis-stack
        env_file: ./discord-bot/.env
        restart: always

