services:
    redis-stack:
        image: redis/redis-stack:latest
        restart: always
        ports:
          # - "6379:6379" # Redis
          - "13333:8001" # RedisInsight
        volumes:
          - ./redis/:/data

    dashboard:
        build: ./dashboard
        depends_on: redis-stack
        env_file: ./dashboard/.env.local
        restart: always

    discord-bot:
        build: ./discord-bot
        depends_on: redis-stack
        env_file: ./discord-bot/.env
        restart: always

